// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiZYpavqxeSIU2lgMew8cHje7asvD2AxM',
    appId: '1:661380718059:web:6b9220b6a166bcfea70dae',
    messagingSenderId: '661380718059',
    projectId: 'budget-bf8f4',
    authDomain: 'budget-bf8f4.firebaseapp.com',
    storageBucket: 'budget-bf8f4.firebasestorage.app',
    measurementId: 'G-23J043VWMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF_3OnXJ4i72W7Ex7FxD5vgTRBfm6KRog',
    appId: '1:661380718059:android:67289501f59dba8ba70dae',
    messagingSenderId: '661380718059',
    projectId: 'budget-bf8f4',
    storageBucket: 'budget-bf8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB48f3PKL_E-GZvm3th93Edv5UUuCs45U',
    appId: '1:661380718059:ios:86ce3fb4e8aec202a70dae',
    messagingSenderId: '661380718059',
    projectId: 'budget-bf8f4',
    storageBucket: 'budget-bf8f4.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB48f3PKL_E-GZvm3th93Edv5UUuCs45U',
    appId: '1:661380718059:ios:86ce3fb4e8aec202a70dae',
    messagingSenderId: '661380718059',
    projectId: 'budget-bf8f4',
    storageBucket: 'budget-bf8f4.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiZYpavqxeSIU2lgMew8cHje7asvD2AxM',
    appId: '1:661380718059:web:4177a7c7f90835c4a70dae',
    messagingSenderId: '661380718059',
    projectId: 'budget-bf8f4',
    authDomain: 'budget-bf8f4.firebaseapp.com',
    storageBucket: 'budget-bf8f4.firebasestorage.app',
    measurementId: 'G-QVTL08L82B',
  );
}
